### ISSUE TITLE
Modul-Unterstützung v2

### ISSUE THREAD

**Issue by Marvv90** [Johannes-Schiel/ud-basic-dev-env#11]
Hallo erstmal & danke für deine Tutorials, 

Wenn ich versuche ein Modul zu importieren bekomme ich die Fehlermeldung ( Can't find variable: require ).

Ich habe versucht die FakerJS ins laufen zu bekommen als auch GSAP oder SWIPER.

Wenn ich mir die komprimierte main.min.js anschaue macht er mir aus:

`import * as faker from 'faker';`

`function _typeof(e){return(_typeof="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e})(e)}var faker=_interopRequireWildcard(require("faker"));function _getRequireWildcardCache(){if("function"!=typeof WeakMap)return null;var e=new WeakMap;return _getRequireWildcardCache=function(){return e},e}function _interopRequireWildcard(e){if(e&&e.__esModule)return e;if(null===e||"object"!==_typeof(e)&&"function"!=typeof e)return{default:e};var t=_getRequireWildcardCache();if(t&&t.has(e))return t.get(e);var r={},n=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var o in e)if(Object.prototype.hasOwnProperty.call(e,o)){var i=n?Object.getOwnPropertyDescriptor(e,o):null;i&&(i.get||i.set)?Object.defineProperty(r,o,i):r[o]=e[o]}return r.default=e,t&&t.set(e,r),r}`

.jshintrc hätt ich 

Ich hoffe ihr könnt mir helfen ! 

LG

**Comment by Johannes-Schiel** [comment]
Sollte jetzt Funktionieren.

**Comment by Marvv90** [comment]
> Sollte jetzt Funktionieren.

Ja , danke dir ! 👍
