### ISSUE TITLE
Font Awesome Font kopieren

### ISSUE THREAD

**Issue by jensen1206** [Johannes-Schiel/ud-basic-dev-env#5]
const fonts = () => {
  return gulp.src(`${src}/fonts/fontawesome-webfont.*`)
  .pipe(gulp.dest(`${dest}/fonts/`));
};

**Comment by Johannes-Schiel** [comment]
Hmmm also bei mir kann ich durch diesen Code jede Art von File copieren

```
gulp.task('copy', function() {
  return gulp.src('./src/data/<filename>.<filetype>')
    .pipe(gulp.dest('./deploy/data'));
});
```

**Comment by Johannes-Schiel** [comment]
Wegen inaktivität wird das Issue geschlossen.
