### ISSUE TITLE
Nunjucks

### ISSUE THREAD

**Issue by h9040335** [Johannes-Schiel/ud-basic-dev-env#8]
Ich habe vieles in meinen Workflow übernommen, funktioniert super :-)
Seit ich Nunjucks im HTML-Teil mit verwende, muss ich immer 2x speichern damit die Änderung in der .njk-Datei korrekt über die .html-Datei im dest-Ordner über browsersync angezeigt wird.
Wo liegt der Fehler?

// Import everything important
const gulp = require(`gulp`);
const plumber = require(`gulp-plumber`);
const rename = require(`gulp-rename`);
const browserSync = require(`browser-sync`).create();
const gutil = require(`gulp-util`);
const sourcemaps = require(`gulp-sourcemaps`);

// For SASS -> CSS
const sass = require(`gulp-sass`);
const postcss = require(`gulp-postcss`);
const autoprefixer = require(`autoprefixer`);
const cssnano = require(`cssnano`);
const sassLint = require(`gulp-sass-lint`);

// HTML
const htmlmin = require(`gulp-htmlmin`);
const nunjucks = require(`gulp-nunjucks`);

// JavaScript/TypeScript
const browserify = require(`gulp-browserify`);
const babel = require(`gulp-babel`);
const jshint = require(`gulp-jshint`);
const uglify = require(`gulp-uglify`);
const concat = require(`gulp-concat`);

// Define Important Varaibles
const src = `./src`;
const dest = `./dest`;

// Function for serve the dev server in browser
const serve = (done) => {
    browserSync.init({
        server: {
            baseDir: `${dest}`
        }
    });
    done();
};

// Function for reload the Browser
const reload = (done) => {
    browserSync.reload();
    done();
};

// Compile .html to minify .html
const html = () => {
    // Nunjucks -> HTML
    gulp.src(`${src}/*.njk`)
        .pipe(nunjucks.compile())
        .pipe(rename({ extname: `.html` }))
        .pipe(gulp.dest(`${src}`));
    // Find HTML
    return gulp.src(`${src}/*.html`)
        // Init Plumber
        .pipe(plumber())
        // HTML -> HTMLmin
        .pipe(htmlmin({
            collapseWhitespace: true,
            removeComments: true,
            html5: true,
            removeEmptyAttributes: true,
            removeTagWhitespace: true,
            sortAttributes: true
        }))
        // Write everything to destination folder
        .pipe(gulp.dest(`${dest}`));
};

// Compile SASS into CSS
const css = () => {
    // Find SASS
    return gulp.src(`${src}/sass/**/*.sass`)
        // Init Plumber
        .pipe(plumber())
        // Lint SASS
        .pipe(sassLint({
            options: {
                formatter: 'stylish',
            },
            rules: {
                'no-ids': 1,
                'final-newline': 0,
                'no-mergeable-selectors': 1,
                'indentation': 0
            }
        }))
        // Format SASS
        .pipe(sassLint.format())
        // Start Source Map
        .pipe(sourcemaps.init())
        // Compile SASS -> CSS
        .pipe(sass.sync({
            outputStyle: `compressed`
        })).on('error', sass.logError)
        // Add Suffix
        .pipe(rename({
            basename: 'all',
            suffix: '.min'
        }))
        // Add Autoprefixer & cssNano
        .pipe(postcss([autoprefixer(), cssnano()]))
        // Write Source Map
        .pipe(sourcemaps.write(''))
        // Write everything to destination folder
        .pipe(gulp.dest(`${dest}/assets/css`))
        // Reload Page
        .pipe(browserSync.stream());
};

// Compile .js to minify .js
const script = () => {
    // Find JavaScript
    return gulp.src(`${src}/assets/js/**/*.js`)
        // Init Plumber
        .pipe(plumber(((error) => {
            gutil.log(error.message);
        })))
        // Start using source maps
        .pipe(sourcemaps.init())
        // concat
        .pipe(concat('concat.js'))
        // Use Babel
        .pipe(babel())
        // JavaScript Lint
        .pipe(jshint())
        // Report of jslint
        .pipe(jshint.reporter('jshint-stylish'))
        // Add browser Support
        .pipe(browserify({
            insertGlobals: true
        }))
        // Minify
        .pipe(uglify())
        // add SUffix
        .pipe(rename({
            basename: 'all',
            suffix: `.min`
        }))
        // Write Sourcemap
        .pipe(sourcemaps.write(''))
        // Write everything to destination folder
        .pipe(gulp.dest(`${dest}/assets/js`))
        // Update Browser
        .pipe(browserSync.stream());
};

// Function to watch our Changes and refreash page
const watch = () => gulp.watch([`${src}/*.njk`, `${src}/sass/**/*.sass`, `${src}/assets/js/**/*.js`], gulp.parallel(html, css, script, reload));

// All Tasks for this Project
const dev = gulp.parallel(html, css, script, serve, watch);

// Just build the project
const build = gulp.series(html, css, script);

// Default function (used when type gulp)
exports.dev = dev;
exports.build = build;
exports.default = build;

**Comment by Johannes-Schiel** [comment]
Also habe es grade bei mir so eingefügt und das Funktioniert wenn ich es abspeicher das es direkt alles läd. Funktioniert es bei dir mitlerweile?

**Comment by h9040335** [comment]
Hallo Johannes,
läuft alles prima mit dieser Konfiguration:

// Import everything important
const gulp = require(`gulp`);
const plumber = require(`gulp-plumber`);
const rename = require(`gulp-rename`);
const browserSync = require(`browser-sync`).create();
const gutil = require(`gulp-util`);
const sourcemaps = require(`gulp-sourcemaps`);

// SASS -> CSS
const sass = require(`gulp-sass`);
const postcss = require(`gulp-postcss`);
const autoprefixer = require(`autoprefixer`);
const cssnano = require(`cssnano`);
const sassLint = require(`gulp-sass-lint`);

// HTML
const nunjucks = require(`gulp-nunjucks`);
const htmlmin = require(`gulp-htmlmin`);
const htmlbeautify = require('gulp-html-beautify');

// JavaScript / TypeScript
const browserify = require(`gulp-browserify`);
const babel = require(`gulp-babel`);
const jshint = require(`gulp-jshint`);
const uglify = require(`gulp-uglify`);
const concat = require(`gulp-concat`);

// Define Important Varaibles
const src = `./src`;
const dest = `./dest`;

// Function for serve the dev server in browser
const serve = (done) => {
    browserSync.init({
        server: {
            baseDir: `${dest}`
        }
    });
    done();
};

// Function for reload the browser
const reload = (done) => {
    browserSync.reload();
    done();
};

// Compile Nunjucks to HTML
const njk = () => {
    return gulp.src(`${src}/assets/templates/*.njk`)
        .pipe(nunjucks.compile())
        .pipe(rename({
            extname: `.html`
        }))
        .pipe(gulp.dest(`${src}`));
};

// Beautify HTML
const beautify = () => {
    return gulp.src(`${src}/*.html`)
        .pipe(htmlbeautify({
            indent_size: 2,
            end_with_newline: false
        }))
        .pipe(gulp.dest(`${src}`));
};

// Compile .html to minify .html
const html = () => {
    return gulp.src(`${src}/*.html`)
        .pipe(plumber())
        .pipe(htmlmin({
            //collapseWhitespace: true,
            removeComments: true,
            html5: true,
            removeEmptyAttributes: true,
            removeTagWhitespace: true,
            sortAttributes: true
        }))
        .pipe(gulp.dest(`${dest}`));
};

// Compile SASS to CSS
const css = () => {
    return gulp.src(`${src}/sass/**/*.sass`)
        .pipe(plumber())
        .pipe(sassLint({
            options: {
                formatter: 'stylish',
            },
            rules: {
                'no-ids': 1,
                'final-newline': 0,
                'no-mergeable-selectors': 1,
                'indentation': 0
            }
        }))
        .pipe(sassLint.format())
        .pipe(sourcemaps.init())
        .pipe(sass.sync({
            outputStyle: `compressed`
        })).on('error', sass.logError)
        .pipe(rename({
            basename: 'all',
            suffix: '.min'
        }))
        .pipe(postcss([autoprefixer(), cssnano()]))
        .pipe(sourcemaps.write(''))
        .pipe(gulp.dest(`${dest}/assets/css`));
};

// Compile .js to minify .js
const script = () => {
    return gulp.src(`${src}/assets/js/**/*.js`)
        .pipe(plumber(((error) => {
            gutil.log(error.message);
        })))
        .pipe(sourcemaps.init())
        .pipe(concat('concat.js'))
        .pipe(babel({
            presets: ['@babel/preset-env']
        }))
        .pipe(jshint())
        .pipe(jshint.reporter('jshint-stylish'))
        .pipe(uglify())
        .pipe(rename({
            basename: 'all',
            suffix: `.min`
        }))
        .pipe(sourcemaps.write(''))
        .pipe(gulp.dest(`${dest}/assets/js`))
        .pipe(browserSync.stream());
};

// Function to watch our changes and refresh page
const watch = () => gulp.watch([`${src}/**/*.njk`, `${src}/sass/**/*.sass`, `${src}/assets/js/**/*.js`], gulp.series(njk, beautify, html, css, script, reload));

// All Tasks for this project
const dev = gulp.series(njk, beautify, html, css, script, serve, watch);

// Just build the project
const build = gulp.series(njk, beautify, html, css, script);

// Default function (used when type gulp)
exports.dev = dev;
exports.build = build;
exports.default = build;

Danke und glg
Jürgen

**Comment by Johannes-Schiel** [comment]
ok super, dann schließe ich den Fehler jetzt.

Als Tipp wenn du 3x ` am anfang und am Ende machst sieht dein Code aus wie ein Codeblock

```
// Import everything important
const gulp = require(gulp);
const plumber = require(gulp-plumber);
const rename = require(gulp-rename);
const browserSync = require(browser-sync).create();
const gutil = require(gulp-util);
const sourcemaps = require(gulp-sourcemaps);

// SASS -> CSS
const sass = require(gulp-sass);
const postcss = require(gulp-postcss);
const autoprefixer = require(autoprefixer);
const cssnano = require(cssnano);
const sassLint = require(gulp-sass-lint);

// HTML
const nunjucks = require(gulp-nunjucks);
const htmlmin = require(gulp-htmlmin);
const htmlbeautify = require('gulp-html-beautify');

// JavaScript / TypeScript
const browserify = require(gulp-browserify);
const babel = require(gulp-babel);
const jshint = require(gulp-jshint);
const uglify = require(gulp-uglify);
const concat = require(gulp-concat);

// Define Important Varaibles
const src = ./src;
const dest = ./dest;

// Function for serve the dev server in browser
const serve = (done) => {
browserSync.init({
server: {
baseDir: ${dest}
}
});
done();
};

// Function for reload the browser
const reload = (done) => {
browserSync.reload();
done();
};

// Compile Nunjucks to HTML
const njk = () => {
return gulp.src(${src}/assets/templates/*.njk)
.pipe(nunjucks.compile())
.pipe(rename({
extname: .html
}))
.pipe(gulp.dest(${src}));
};

// Beautify HTML
const beautify = () => {
return gulp.src(${src}/*.html)
.pipe(htmlbeautify({
indent_size: 2,
end_with_newline: false
}))
.pipe(gulp.dest(${src}));
};

// Compile .html to minify .html
const html = () => {
return gulp.src(${src}/*.html)
.pipe(plumber())
.pipe(htmlmin({
//collapseWhitespace: true,
removeComments: true,
html5: true,
removeEmptyAttributes: true,
removeTagWhitespace: true,
sortAttributes: true
}))
.pipe(gulp.dest(${dest}));
};

// Compile SASS to CSS
const css = () => {
return gulp.src(${src}/sass/**/*.sass)
.pipe(plumber())
.pipe(sassLint({
options: {
formatter: 'stylish',
},
rules: {
'no-ids': 1,
'final-newline': 0,
'no-mergeable-selectors': 1,
'indentation': 0
}
}))
.pipe(sassLint.format())
.pipe(sourcemaps.init())
.pipe(sass.sync({
outputStyle: compressed
})).on('error', sass.logError)
.pipe(rename({
basename: 'all',
suffix: '.min'
}))
.pipe(postcss([autoprefixer(), cssnano()]))
.pipe(sourcemaps.write(''))
.pipe(gulp.dest(${dest}/assets/css));
};

// Compile .js to minify .js
const script = () => {
return gulp.src(${src}/assets/js/**/*.js)
.pipe(plumber(((error) => {
gutil.log(error.message);
})))
.pipe(sourcemaps.init())
.pipe(concat('concat.js'))
.pipe(babel({
presets: ['@babel/preset-env']
}))
.pipe(jshint())
.pipe(jshint.reporter('jshint-stylish'))
.pipe(uglify())
.pipe(rename({
basename: 'all',
suffix: .min
}))
.pipe(sourcemaps.write(''))
.pipe(gulp.dest(${dest}/assets/js))
.pipe(browserSync.stream());
};

// Function to watch our changes and refresh page
const watch = () => gulp.watch([${src}/**/*.njk, ${src}/sass/**/*.sass, ${src}/assets/js/**/*.js], gulp.series(njk, beautify, html, css, script, reload));

// All Tasks for this project
const dev = gulp.series(njk, beautify, html, css, script, serve, watch);

// Just build the project
const build = gulp.series(njk, beautify, html, css, script);

// Default function (used when type gulp)
exports.dev = dev;
exports.build = build;
exports.default = build;
```
